import exp from "express";
import { currentUser, loginUser, logoutUser, registerUser, updateAccountDetails } from "../controller/userController.js";
import { authmiddleware } from "../helper/auth.js";
const router = exp.Router();
router.post("/login", loginUser);
router.post('/register', registerUser);
router.get('/me', authmiddleware, currentUser);
router.get('/logout',authmiddleware,logoutUser);
router.patch('/updatedetails', authmiddleware , updateAccountDetails);
export default router;